services:
  - type: web
    name: grading-system-backend
    runtime: docker
    plan: free
    region: singapore
    healthCheckPath: /v3/api-docs
    autoDeployTrigger: commit
    envVars:
      - key: DB_HOST
        value: 127.0.0.1
      - key: DB_PORT
        value: "3306"
      - key: DB_NAME
        value: grading_system
      - key: DB_USER
        value: grading_user
      - key: DB_PASSWORD
        generateValue: true
      - key: SPRING_JPA_SHOW_SQL
        value: "false"
